"use client";

import { useState } from "react";
import ProtectedRoute from "@/components/auth/ProtectedRoute";
import EnterpriseLayout from "@/components/layout/EnterpriseLayout";
import CaseTable from "@/components/cases/CaseTable";
import { useCases } from "@/hooks/useCases";
import { CaseFilterParams } from "@/types/investigation";
import { ShieldAlert, Search, PlusCircle, Download, Layers, ChevronLeft, ChevronRight, Activity, AlertOctagon } from "lucide-react";
import Link from "next/link";
import { useToast } from "@/components/ui/toast";

export default function CasesDirectoryPage() {
  const [filters, setFilters] = useState<CaseFilterParams>({
    page: 1,
    size: 10,
    search: "",
  });

  const { data, isLoading } = useCases(filters);
  const { showToast } = useToast();

  const handleFilterChange = (newFilters: Partial<CaseFilterParams>) => {
    setFilters((prev) => ({ ...prev, ...newFilters }));
  };

  const handleExportCsv = () => {
    if (!data?.items || data.items.length === 0) {
      showToast("No investigation cases available to export for current filters", "warning");
      return;
    }
    const headers = ["Case ID", "Transaction ID", "Title", "Priority", "Status", "Category", "Opened At"];
    const rows = data.items.map((c) => [
      c.case_id,
      c.transaction_id,
      `"${c.case_title}"`,
      c.priority,
      c.status,
      c.category,
      c.opened_at,
    ]);
    const csvContent = "data:text/csv;charset=utf-8," + [headers.join(","), ...rows.map((e) => e.join(","))].join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `RiskShield_Investigation_Cases_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    showToast("CSV export generated successfully!", "info");
  };

  return (
    <ProtectedRoute>
      <EnterpriseLayout>
        <div className="space-y-6">
          {/* Page Header */}
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-6 sm:mb-8 gap-4 w-full">
            <div className="min-w-0">
              <div className="flex items-center space-x-2 text-xs font-semibold text-copper-400 mb-1">
                <ShieldAlert className="w-4 h-4 text-copper-400 shrink-0" />
                <span className="truncate">Enterprise Investigation Platform</span>
              </div>
              <h1 className="text-xl sm:text-2xl font-bold text-white tracking-tight truncate">
                Fraud Analyst Case Management Workspace
              </h1>
              <p className="text-xs text-graphite-400 mt-1">
                Investigate, assign, resolve, and audit suspicious transaction alerts generated by RiskShield AI.
              </p>
            </div>

            <div className="flex flex-wrap items-center gap-2 sm:gap-3 w-full sm:w-auto shrink-0">
              <button
                onClick={handleExportCsv}
                className="px-4 py-2.5 bg-graphite-900 border border-graphite-800 hover:bg-graphite-800 text-copper-400 font-semibold text-xs rounded-lg transition-colors flex items-center space-x-2 shrink-0"
              >
                <Download className="w-4 h-4" />
                <span>Export CSV</span>
              </button>

              <Link
                href="/cases/new"
                className="px-4 py-2.5 bg-copper-500 hover:bg-copper-400 text-graphite-950 font-bold text-xs rounded-lg transition-colors flex items-center space-x-2 shrink-0"
              >
                <PlusCircle className="w-4 h-4 fill-graphite-950" />
                <span>Create Investigation Case</span>
              </Link>
            </div>
          </div>

          {/* Case Statistics Cards */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
            <div className="bg-graphite-900 border border-graphite-800 rounded-xl p-4 shadow-sm">
              <span className="text-[10px] uppercase font-bold text-graphite-400">Total Cases</span>
              <p className="text-2xl font-bold text-white font-mono mt-1">{data?.total || 0}</p>
            </div>

            <div className="bg-graphite-900 border border-graphite-800 rounded-xl p-4 shadow-sm">
              <span className="text-[10px] uppercase font-bold text-amber-400">Open & Active</span>
              <p className="text-2xl font-bold text-amber-400 font-mono mt-1">
                {data?.items?.filter((c) => c.status === "OPEN" || c.status === "ASSIGNED" || c.status === "UNDER_INVESTIGATION").length || 0}
              </p>
            </div>

            <div className="bg-graphite-900 border border-graphite-800 rounded-xl p-4 shadow-sm">
              <span className="text-[10px] uppercase font-bold text-rose-400">Critical Priority</span>
              <p className="text-2xl font-bold text-rose-400 font-mono mt-1">
                {data?.items?.filter((c) => c.priority === "CRITICAL").length || 0}
              </p>
            </div>

            <div className="bg-graphite-900 border border-graphite-800 rounded-xl p-4 shadow-sm">
              <span className="text-[10px] uppercase font-bold text-emerald-400">Resolved Cases</span>
              <p className="text-2xl font-bold text-emerald-400 font-mono mt-1">
                {data?.items?.filter((c) => c.status === "RESOLVED" || c.status === "CLOSED").length || 0}
              </p>
            </div>
          </div>

          {/* Search Bar */}
          <div className="bg-graphite-900 border border-graphite-800 rounded-xl p-4 mb-6 shadow-sm flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="relative w-full sm:w-96">
              <input
                type="text"
                placeholder="Search cases by ID, title, or transaction..."
                value={filters.search || ""}
                onChange={(e) => handleFilterChange({ search: e.target.value, page: 1 })}
                className="w-full pl-10 pr-4 py-2 bg-graphite-950 border border-graphite-700 rounded-lg text-graphite-100 text-xs placeholder-graphite-500 focus:outline-none focus:ring-2 focus:ring-copper-400"
              />
              <Search className="w-4 h-4 text-graphite-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
            </div>

            <div className="flex items-center space-x-3 w-full sm:w-auto">
              <select
                value={filters.priority || ""}
                onChange={(e) => handleFilterChange({ priority: e.target.value || undefined, page: 1 })}
                className="px-3 py-2 bg-graphite-950 border border-graphite-700 rounded-lg text-white font-mono text-xs focus:ring-2 focus:ring-copper-400 focus:outline-none"
              >
                <option value="">All Priorities</option>
                <option value="CRITICAL">CRITICAL</option>
                <option value="HIGH">HIGH</option>
                <option value="MEDIUM">MEDIUM</option>
                <option value="LOW">LOW</option>
              </select>

              <select
                value={filters.status || ""}
                onChange={(e) => handleFilterChange({ status: e.target.value || undefined, page: 1 })}
                className="px-3 py-2 bg-graphite-950 border border-graphite-700 rounded-lg text-white font-mono text-xs focus:ring-2 focus:ring-copper-400 focus:outline-none"
              >
                <option value="">All Statuses</option>
                <option value="OPEN">OPEN</option>
                <option value="ASSIGNED">ASSIGNED</option>
                <option value="UNDER_INVESTIGATION">UNDER_INVESTIGATION</option>
                <option value="RESOLVED">RESOLVED</option>
                <option value="CLOSED">CLOSED</option>
              </select>
            </div>
          </div>

          {/* Data Table */}
          <CaseTable cases={data?.items || []} isLoading={isLoading} />

          {/* Pagination Controls */}
          {data && data.pages > 1 && (
            <div className="flex items-center justify-between mt-6 bg-graphite-900 border border-graphite-800 rounded-xl px-4 py-3 text-xs text-graphite-400">
              <div>
                Page <span className="font-semibold text-white">{data.page}</span> of{" "}
                <span className="font-semibold text-white">{data.pages}</span> ({data.total} total cases)
              </div>
              <div className="flex items-center space-x-2">
                <button
                  disabled={data.page <= 1}
                  onClick={() => handleFilterChange({ page: data.page - 1 })}
                  className="p-1.5 rounded-lg bg-graphite-800 hover:bg-graphite-700 disabled:opacity-40 text-graphite-300 transition-colors"
                >
                  <ChevronLeft className="w-4 h-4" />
                </button>
                <button
                  disabled={data.page >= data.pages}
                  onClick={() => handleFilterChange({ page: data.page + 1 })}
                  className="p-1.5 rounded-lg bg-graphite-800 hover:bg-graphite-700 disabled:opacity-40 text-graphite-300 transition-colors"
                >
                  <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          )}
        </div>
      </EnterpriseLayout>
    </ProtectedRoute>
  );
}
