from enum import Enum


class EventType(str, Enum):
    TRANSACTION_CREATED = "TRANSACTION_CREATED"
    TRANSACTION_FAILED = "TRANSACTION_FAILED"
    HIGH_RISK_TRANSACTION = "HIGH_RISK_TRANSACTION"
    DECISION_GENERATED = "DECISION_GENERATED"
    MODEL_PREDICTION = "MODEL_PREDICTION"
    CASE_CREATED = "CASE_CREATED"
    CASE_ASSIGNED = "CASE_ASSIGNED"
    CASE_CLOSED = "CASE_CLOSED"
    RULE_PUBLISHED = "RULE_PUBLISHED"
    MERCHANT_CREATED = "MERCHANT_CREATED"
    DEVICE_FLAGGED = "DEVICE_FLAGGED"
    CUSTOMER_FLAGGED = "CUSTOMER_FLAGGED"


class NotificationPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class NotificationChannel(str, Enum):
    IN_APP = "IN_APP"
    EMAIL = "EMAIL"
    WEBHOOK = "WEBHOOK"
    WEBSOCKET = "WEBSOCKET"
